development:
  email_provider_username: dengel29@gmail.com
  email_provider_password: Dd13438128297Ee
  mailchimp_api_key: f46271f0515083e75d71163ab9467fb1-us8
  domain_name: example.com
  mailchimp_list_id: e00a251248
  owner_email: dengel29@gmail.com
  secret_key_base: 8ddb93c572b40ed03dfacffb52a6e42ceb5d44e421486e754447cba38ef395249955326cc92ce19aa4df5e1608e06a8d610ba8da6e5f279615a82020261c0db0

test:
  secret_key_base: 917760dd38c886bce79ddc9b96a6e7a7b698f93756bcbbd3f2c2e8201b961ba39a79c9238378337f309ce948dd6d21b83b590a7ea544622b9f9b5721dfa3b632

production:
  email_provider_username: <%= ENV["GMAIL_USERNAME"] %>
  email_provider_password: <%= ENV["GMAIL_PASSWORD"] %>
  mailchimp_api_key: <%= ENV["mailchimp_api_key"] %>
  domain_name: example.com
  mailchimp_list_id: <%= ENV["mailchimp_list_id"] %>
  owner_email: <%= ENV["owner_email"] %>
  secret_key_base: very_long_string